/* Malaysia's national-language notice is additional to the five UI locales. */
export function MalaysiaNotice() {
  return <section id="malaysia-notice" className="site-section max-w-3xl" aria-labelledby="malaysia-notice-heading">
    <h2 id="malaysia-notice-heading" className="site-section__heading">Notis privasi — Bahasa Malaysia / English</h2>
    <div lang="ms" className="site-section__intro">
      <p>Money Nerds mengendalikan papan awam untuk permintaan dan sokongan terus secara sukarela. Untuk pertanyaan privasi, akses, pembetulan atau penarikan balik persetujuan, hubungi <a href="mailto:unluckypleasure@yandex.ru">unluckypleasure@yandex.ru</a>. Identiti undang-undang dan alamat pengendali serta pegawai perlindungan data yang diperlukan belum disahkan. Notis ini tidak mendakwa bahawa semua kewajipan undang-undang telah dipenuhi.</p>
      <p>Data yang digunakan termasuk pengecam akaun dan butiran profil daripada penyedia log masuk; siaran, komen, reaksi dan media yang anda berikan; alamat penerimaan dan rekod transaksi; pilihan bahasa, negara dan kuki; serta maklumat teknikal untuk keselamatan. Tujuannya ialah menyediakan akaun, memaparkan kandungan, menyokong pemindahan yang anda minta, menyesuaikan antara muka dan melindungi perkhidmatan. Data juga boleh diperoleh daripada transaksi rantaian blok yang awam.</p>
      <p>Profil, siaran, komen, media dan aktiviti kripto yang dipautkan adalah awam. Butiran SBP pilihan merangkumi nombor telefon dan bank penerima; pengguna yang layak boleh melihat dan menyalinnya. Clerk mengendalikan pengesahan, Supabase menyediakan pangkalan data dan storan media, dan Vercel mengehos laman. Telegram, bank, dompet, rangkaian dan penyedia e-mel memproses maklumat apabila anda menggunakan perkhidmatan mereka. Penerima mungkin berada di luar Malaysia; pengaturan pemindahan dan tempoh simpanan penuh masih perlu disahkan.</p>
      <p>Anda tidak perlu memberikan data untuk sekadar membaca papan awam. Pengecam akaun diperlukan untuk log masuk dan tindakan akaun; tanpa data tersebut, fungsi itu tidak tersedia. Siaran dan media ialah pilihan. Maklumat SBP hanya diperlukan jika anda memilih untuk menerimanya. Penyimpanan kiraan paparan adalah pilihan dan boleh ditolak atau ditarik balik melalui pilihan privasi. Kuki pilihan bahasa, negara, privasi dan kiraan paparan pilihan bertahan sehingga 180 hari.</p>
      <p>Untuk meminta akses, pembetulan, pemadaman atau butiran pemprosesan, nyatakan akaun atau URL yang berkaitan melalui alamat e-mel di atas. Jangan hantar kata laluan, kod log masuk atau dokumen pengenalan dalam e-mel pertama. Pengesahan mungkin diperlukan. Penarikan persetujuan pilihan tidak memadam rekod rantaian blok atau salinan pihak lain. Anda boleh menghubungi Pesuruhjaya Perlindungan Data Peribadi Malaysia di <a href="https://www.pdp.gov.my/">www.pdp.gov.my</a>.</p>
    </div>
    <div lang="en" className="site-section__intro mt-8">
      <p>Money Nerds runs a public board for requests and voluntary direct support. Contact unluckypleasure@yandex.ru for privacy questions, access, correction or withdrawal. The operator’s legal identity, address and any required data-protection officer remain unverified; this notice does not certify completion of those duties.</p>
      <p>We use account identifiers and profile details supplied by sign-in providers; your posts, comments, reactions and media; receiving addresses and transaction records; language, country and cookie preferences; and technical security information. Purposes include accounts, public content, requested transfer support, interface preferences and service protection. Public blockchain transactions are another source.</p>
      <p>Profiles, posts, comments, media and linked crypto activity are public. Optional SBP phone and bank details can be viewed and copied by eligible users. Clerk handles authentication, Supabase database/media storage, and Vercel hosting. Telegram, banks, wallets, networks and email providers process information when used. Recipients may be outside Malaysia; transfer arrangements and the full retention schedule remain to be verified.</p>
      <p>You can read the public board without supplying account data. Account identifiers are necessary for sign-in and account actions; without them those features are unavailable. Posts/media are optional. SBP details are needed only if you choose to receive through SBP. View counting is optional and can be declined or withdrawn through Privacy choices. Language, country, privacy and optional view cookies last up to 180 days.</p>
      <p>For access, correction, deletion or processing details, identify the relevant account or URL in an email to the contact above. Do not send passwords, sign-in codes or identity documents in the first email. Verification may be required. Withdrawal does not erase blockchain records or copies held elsewhere. You may contact Malaysia’s Personal Data Protection Commissioner at www.pdp.gov.my.</p>
    </div>
  </section>;
}
