-- Money Nerds production data model.
--
-- This migration is deliberately additive. The legacy posts, post_info, comments,
-- and main_test tables and their original columns remain available for rollback,
-- while normalized columns/tables are populated from the legacy data.
--
-- Authentication is wallet-only and server mediated. Raw session tokens must never
-- be stored; the application stores only a SHA-256 hex digest in
-- public.wallet_sessions (an RLS-closed internal table) and keeps the raw token
-- in an HttpOnly cookie.

begin;

create extension if not exists pgcrypto with schema extensions;

create schema if not exists internal;
revoke all on schema internal from public, anon, authenticated;
grant usage on schema internal to service_role;

-- A fresh local Supabase database has no legacy migrations to replay. These
-- definitions mirror the production baseline and are no-ops against production.
create table if not exists public.posts (
  message text,
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  username varchar,
  image_url text,
  "walletAddress" text,
  donated_sum double precision default 0,
  donated jsonb default '{}'::jsonb,
  likes bigint default 0
);

create table if not exists public.post_info (
  created_at timestamptz not null default now(),
  liked_by text[],
  donated jsonb default '{}'::jsonb,
  id bigint generated by default as identity primary key
);

create table if not exists public.comments (
  user_id text,
  user_nickname text,
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  content text,
  post_id bigint,
  likes text[],
  image text
);

create table if not exists public.main_test (
  content text,
  created_at timestamptz not null default now(),
  user_id uuid default gen_random_uuid(),
  id bigint generated by default as identity primary key
);

-- The old unique(message) constraint rejected two unrelated posts with identical
-- text. Keep the legacy message column, but remove that accidental constraint.
alter table public.posts drop constraint if exists test_message_key;
alter table public.posts drop constraint if exists posts_message_key;

create table if not exists public.profiles (
  wallet_address text primary key,
  display_name text,
  bio text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_wallet_address_shape check (
    wallet_address ~ '^[1-9A-HJ-NP-Za-km-z]{32,44}$'
  ),
  constraint profiles_display_name_length check (
    display_name is null or char_length(display_name) between 1 and 80
  ),
  constraint profiles_bio_length check (
    bio is null or char_length(bio) <= 1000
  )
);

-- Create one durable profile for every syntactically valid wallet found anywhere
-- in the legacy system. Content continues to reference the profile when a wallet
-- later creates a new server-side session.
with wallet_events as (
  select btrim(p."walletAddress") as wallet_address, p.created_at as seen_at
  from public.posts p
  where btrim(coalesce(p."walletAddress", '')) ~ '^[1-9A-HJ-NP-Za-km-z]{32,44}$'
  union all
  select btrim(c.user_id), c.created_at
  from public.comments c
  where btrim(coalesce(c.user_id, '')) ~ '^[1-9A-HJ-NP-Za-km-z]{32,44}$'
  union all
  select btrim(l.wallet_address), pi.created_at
  from public.post_info pi
  cross join lateral unnest(coalesce(pi.liked_by, array[]::text[])) as l(wallet_address)
  where btrim(coalesce(l.wallet_address, '')) ~ '^[1-9A-HJ-NP-Za-km-z]{32,44}$'
  union all
  select btrim(d.key), p.created_at
  from public.posts p
  cross join lateral jsonb_each(
    case when jsonb_typeof(p.donated) = 'object' then p.donated else '{}'::jsonb end
  ) as d(key, value)
  where btrim(d.key) ~ '^[1-9A-HJ-NP-Za-km-z]{32,44}$'
  union all
  select btrim(u.raw_user_meta_data ->> 'walletAddress'), u.created_at
  from auth.users u
  where btrim(coalesce(u.raw_user_meta_data ->> 'walletAddress', ''))
    ~ '^[1-9A-HJ-NP-Za-km-z]{32,44}$'
), wallets as (
  select wallet_address, min(seen_at) as first_seen_at, max(seen_at) as last_seen_at
  from wallet_events
  group by wallet_address
)
insert into public.profiles (wallet_address, display_name, created_at, updated_at)
select
  w.wallet_address,
  coalesce(
    (
      select nullif(btrim(p.username), '')
      from public.posts p
      where btrim(p."walletAddress") = w.wallet_address
      order by p.created_at desc, p.id desc
      limit 1
    ),
    (
      select nullif(btrim(c.user_nickname), '')
      from public.comments c
      where btrim(c.user_id) = w.wallet_address
      order by c.created_at desc, c.id desc
      limit 1
    )
  ),
  coalesce(w.first_seen_at, now()),
  coalesce(w.last_seen_at, now())
from wallets w
on conflict (wallet_address) do update
set display_name = coalesce(public.profiles.display_name, excluded.display_name),
    updated_at = greatest(public.profiles.updated_at, excluded.updated_at);

-- Retain all old fake-email auth mappings, including duplicate auth users for the
-- same wallet. New custom wallet sessions do not depend on auth.users.
create table if not exists internal.legacy_auth_wallet_links (
  auth_user_id uuid primary key references auth.users(id) on delete cascade,
  wallet_address text not null references public.profiles(wallet_address) on delete restrict,
  linked_at timestamptz not null default now()
);

insert into internal.legacy_auth_wallet_links (auth_user_id, wallet_address, linked_at)
select
  u.id,
  btrim(u.raw_user_meta_data ->> 'walletAddress'),
  coalesce(u.created_at, now())
from auth.users u
where btrim(coalesce(u.raw_user_meta_data ->> 'walletAddress', ''))
  ~ '^[1-9A-HJ-NP-Za-km-z]{32,44}$'
on conflict (auth_user_id) do update
set wallet_address = excluded.wallet_address;

-- Add normalized, strongly constrained post columns without removing the rollback
-- columns username, message, image_url, walletAddress, donated, donated_sum, likes.
alter table public.posts
  add column if not exists author_wallet text,
  add column if not exists nickname text,
  add column if not exists body text,
  add column if not exists category text default 'anything',
  add column if not exists updated_at timestamptz default now(),
  add column if not exists like_count bigint not null default 0,
  add column if not exists legacy_unattributed_like_count bigint not null default 0,
  add column if not exists verified_donation_lamports bigint not null default 0,
  add column if not exists legacy_donation_lamports bigint not null default 0,
  add column if not exists comment_count bigint not null default 0;

do $$
begin
  if exists (
    select 1 from public.posts
    where btrim(coalesce("walletAddress", ''))
      !~ '^[1-9A-HJ-NP-Za-km-z]{32,44}$'
  ) then
    raise exception 'Legacy posts contain an invalid wallet address; migration stopped before backfill';
  end if;
end
$$;

update public.posts
set author_wallet = btrim("walletAddress"),
    nickname = coalesce(nullif(btrim(username), ''), 'Anonymous'),
    body = coalesce(message, ''),
    category = coalesce(nullif(btrim(category), ''), 'anything'),
    updated_at = coalesce(updated_at, created_at);

alter table public.posts
  alter column author_wallet set not null,
  alter column nickname set not null,
  alter column body set not null,
  alter column category set not null,
  alter column category set default 'anything',
  alter column updated_at set not null,
  alter column updated_at set default now();

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'posts_author_wallet_fkey') then
    alter table public.posts
      add constraint posts_author_wallet_fkey
      foreign key (author_wallet) references public.profiles(wallet_address)
      on update cascade on delete restrict;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'posts_body_length') then
    alter table public.posts
      add constraint posts_body_length check (char_length(body) <= 20000);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'posts_nickname_length') then
    alter table public.posts
      add constraint posts_nickname_length check (char_length(nickname) between 1 and 80);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'posts_category_length') then
    alter table public.posts
      add constraint posts_category_length check (
        category in ('anything', 'for-fun', 'mutual-aid', 'build', 'animals', 'art')
      );
  end if;
  if not exists (select 1 from pg_constraint where conname = 'posts_counts_nonnegative') then
    alter table public.posts
      add constraint posts_counts_nonnegative check (
        like_count >= 0 and legacy_unattributed_like_count >= 0
        and verified_donation_lamports >= 0 and legacy_donation_lamports >= 0
        and comment_count >= 0
      );
  end if;
end
$$;

-- Comments support replies through parent_id. Invalid historic author strings are
-- preserved in legacy_author_label; only valid wallets are linked to profiles.
alter table public.comments
  add column if not exists parent_id bigint,
  add column if not exists author_wallet text,
  add column if not exists legacy_author_label text,
  add column if not exists nickname text,
  add column if not exists body text,
  add column if not exists updated_at timestamptz default now(),
  add column if not exists depth smallint not null default 0,
  add column if not exists like_count bigint not null default 0,
  add column if not exists verified_donation_lamports bigint not null default 0;

update public.comments
set author_wallet = case
      when btrim(coalesce(user_id, '')) ~ '^[1-9A-HJ-NP-Za-km-z]{32,44}$'
        then btrim(user_id)
      else null
    end,
    legacy_author_label = case
      when btrim(coalesce(user_id, '')) ~ '^[1-9A-HJ-NP-Za-km-z]{32,44}$'
        then null
      else nullif(btrim(user_id), '')
    end,
    nickname = coalesce(nullif(btrim(user_nickname), ''), 'Anonymous'),
    body = coalesce(content, ''),
    updated_at = coalesce(updated_at, created_at),
    depth = 0;

do $$
begin
  if exists (
    select 1
    from public.comments c
    left join public.posts p on p.id = c.post_id
    where c.post_id is null or p.id is null
  ) then
    raise exception 'Legacy comments contain an orphan post_id; migration stopped before adding the foreign key';
  end if;
end
$$;

alter table public.comments
  alter column post_id set not null,
  alter column nickname set not null,
  alter column body set not null,
  alter column updated_at set not null,
  alter column updated_at set default now();

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'comments_post_id_fkey') then
    alter table public.comments
      add constraint comments_post_id_fkey foreign key (post_id)
      references public.posts(id) on delete cascade;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'comments_parent_id_fkey') then
    alter table public.comments
      add constraint comments_parent_id_fkey foreign key (parent_id)
      references public.comments(id) on delete cascade;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'comments_author_wallet_fkey') then
    alter table public.comments
      add constraint comments_author_wallet_fkey foreign key (author_wallet)
      references public.profiles(wallet_address) on update cascade on delete restrict;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'comments_body_length') then
    alter table public.comments
      add constraint comments_body_length check (char_length(body) <= 10000);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'comments_nickname_length') then
    alter table public.comments
      add constraint comments_nickname_length check (char_length(nickname) between 1 and 80);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'comments_depth_range') then
    alter table public.comments
      add constraint comments_depth_range check (depth between 0 and 5);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'comments_counts_nonnegative') then
    alter table public.comments
      add constraint comments_counts_nonnegative check (
        like_count >= 0 and verified_donation_lamports >= 0
      );
  end if;
  if not exists (select 1 from pg_constraint where conname = 'comments_legacy_author_present') then
    alter table public.comments
      add constraint comments_legacy_author_present check (
        author_wallet is not null or legacy_author_label is not null
      );
  end if;
end
$$;

create table if not exists public.post_likes (
  post_id bigint not null references public.posts(id) on delete cascade,
  wallet_address text not null references public.profiles(wallet_address)
    on update cascade on delete restrict,
  created_at timestamptz not null default now(),
  primary key (post_id, wallet_address)
);

create table if not exists public.comment_likes (
  comment_id bigint not null references public.comments(id) on delete cascade,
  wallet_address text not null references public.profiles(wallet_address)
    on update cascade on delete restrict,
  created_at timestamptz not null default now(),
  primary key (comment_id, wallet_address)
);

insert into public.post_likes (post_id, wallet_address, created_at)
select pi.id, btrim(l.wallet_address), pi.created_at
from public.post_info pi
join public.posts p on p.id = pi.id
cross join lateral unnest(coalesce(pi.liked_by, array[]::text[])) as l(wallet_address)
join public.profiles pr on pr.wallet_address = btrim(l.wallet_address)
where btrim(coalesce(l.wallet_address, '')) ~ '^[1-9A-HJ-NP-Za-km-z]{32,44}$'
group by pi.id, btrim(l.wallet_address), pi.created_at
on conflict (post_id, wallet_address) do nothing;

insert into public.comment_likes (comment_id, wallet_address, created_at)
select c.id, btrim(l.wallet_address), c.created_at
from public.comments c
cross join lateral unnest(coalesce(c.likes, array[]::text[])) as l(wallet_address)
join public.profiles pr on pr.wallet_address = btrim(l.wallet_address)
where btrim(coalesce(l.wallet_address, '')) ~ '^[1-9A-HJ-NP-Za-km-z]{32,44}$'
group by c.id, btrim(l.wallet_address), c.created_at
on conflict (comment_id, wallet_address) do nothing;

with exact_likes as (
  select p.id, count(pl.wallet_address)::bigint as exact_count
  from public.posts p
  left join public.post_likes pl on pl.post_id = p.id
  group by p.id
)
update public.posts p
set legacy_unattributed_like_count = greatest(coalesce(p.likes, 0) - e.exact_count, 0),
    like_count = e.exact_count
from exact_likes e
where e.id = p.id;

update public.comments c
set like_count = x.exact_count
from (
  select c2.id, count(cl.wallet_address)::bigint as exact_count
  from public.comments c2
  left join public.comment_likes cl on cl.comment_id = c2.id
  group by c2.id
) x
where x.id = c.id;

-- New donations are inserted only after a trusted server verifies the Solana
-- transaction. A transaction instruction may be recorded once globally.
create table if not exists public.donations (
  signature text primary key,
  network text not null default 'mainnet-beta',
  instruction_index integer not null default 0,
  donor_wallet text not null references public.profiles(wallet_address)
    on update cascade on delete restrict,
  recipient_wallet text not null,
  target_type text not null,
  post_id bigint references public.posts(id) on delete cascade,
  comment_id bigint references public.comments(id) on delete cascade,
  lamports bigint not null,
  slot bigint,
  status text not null default 'verified',
  verified_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint donations_target_shape check (
    (target_type = 'post' and post_id is not null and comment_id is null)
    or (target_type = 'comment' and comment_id is not null and post_id is null)
    or (target_type = 'service' and post_id is null and comment_id is null)
  ),
  constraint donations_target_type check (target_type in ('post', 'comment', 'service')),
  constraint donations_amount_positive check (lamports > 0),
  constraint donations_instruction_nonnegative check (instruction_index >= 0),
  constraint donations_network check (network in ('mainnet-beta', 'devnet', 'testnet')),
  constraint donations_status check (status = 'verified'),
  constraint donations_signature_shape check (signature ~ '^[1-9A-HJ-NP-Za-km-z]{80,90}$'),
  constraint donations_recipient_shape check (
    recipient_wallet ~ '^[1-9A-HJ-NP-Za-km-z]{32,44}$'
  )
);

-- Historical JSON donation totals have no transaction signature and therefore
-- must never be presented as verified. raw_amount preserves every original value.
create table if not exists public.legacy_unverified_donations (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  donor_wallet text not null,
  recipient_wallet text not null references public.profiles(wallet_address)
    on update cascade on delete restrict,
  amount_lamports bigint,
  raw_amount jsonb not null,
  source text not null default 'posts.donated',
  migrated_at timestamptz not null default now(),
  constraint legacy_unverified_amount_nonnegative check (
    amount_lamports is null or amount_lamports >= 0
  ),
  unique (post_id, donor_wallet, source)
);

insert into public.legacy_unverified_donations (
  post_id, donor_wallet, recipient_wallet, amount_lamports, raw_amount
)
select
  p.id,
  btrim(d.key),
  p.author_wallet,
  case
    when jsonb_typeof(d.value) = 'number'
      and (d.value #>> '{}')::numeric >= 0
      then round((d.value #>> '{}')::numeric * 1000000000)::bigint
    else null
  end,
  d.value
from public.posts p
cross join lateral jsonb_each(
  case when jsonb_typeof(p.donated) = 'object' then p.donated else '{}'::jsonb end
) as d(key, value)
on conflict (post_id, donor_wallet, source) do update
set amount_lamports = excluded.amount_lamports,
    raw_amount = excluded.raw_amount,
    recipient_wallet = excluded.recipient_wallet;

update public.posts p
set legacy_donation_lamports = x.total_lamports
from (
  select p2.id, coalesce(sum(l.amount_lamports), 0)::bigint as total_lamports
  from public.posts p2
  left join public.legacy_unverified_donations l on l.post_id = p2.id
  group by p2.id
) x
where x.id = p.id;

create table if not exists public.media_assets (
  id uuid primary key default gen_random_uuid(),
  owner_wallet text not null references public.profiles(wallet_address)
    on update cascade on delete restrict,
  bucket_id text not null default 'media',
  storage_path text not null unique,
  public_url text not null,
  kind text not null,
  mime_type text not null,
  size_bytes bigint not null,
  width integer,
  height integer,
  duration_seconds numeric(10,3),
  alt_text text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint media_assets_bucket check (bucket_id = 'media'),
  constraint media_assets_kind check (kind in ('image', 'audio', 'video_circle')),
  constraint media_assets_mime_allowed check (mime_type in (
    'image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/avif',
    'audio/webm', 'audio/mpeg', 'audio/mp4', 'audio/ogg', 'audio/wav',
    'video/webm', 'video/mp4', 'video/quicktime'
  )),
  constraint media_assets_mime_matches_kind check (
    (kind = 'image' and mime_type like 'image/%')
    or (kind = 'audio' and mime_type like 'audio/%')
    or (kind = 'video_circle' and mime_type like 'video/%')
  ),
  constraint media_assets_size check (size_bytes between 1 and 15728640),
  constraint media_assets_dimensions check (
    (width is null or width > 0) and (height is null or height > 0)
  ),
  constraint media_assets_duration check (duration_seconds is null or duration_seconds > 0),
  constraint media_assets_owner_path check (storage_path like owner_wallet || '/%'),
  constraint media_assets_public_url check (public_url ~ '^https://'),
  constraint media_assets_alt_text_length check (alt_text is null or char_length(alt_text) <= 500)
);

create table if not exists public.post_media (
  post_id bigint not null references public.posts(id) on delete cascade,
  media_id uuid not null references public.media_assets(id) on delete cascade,
  position smallint not null default 0,
  created_at timestamptz not null default now(),
  primary key (post_id, media_id),
  unique (post_id, position),
  constraint post_media_position check (position between 0 and 15)
);

create table if not exists public.comment_media (
  comment_id bigint not null references public.comments(id) on delete cascade,
  media_id uuid not null references public.media_assets(id) on delete cascade,
  position smallint not null default 0,
  created_at timestamptz not null default now(),
  primary key (comment_id, media_id),
  unique (comment_id, position),
  constraint comment_media_position check (position between 0 and 15)
);

-- Challenge rows are short-lived and single-use. The full signed message is kept
-- so the server verifies exactly what it issued, not a client-supplied variant.
create table if not exists public.wallet_challenges (
  id uuid primary key default gen_random_uuid(),
  wallet_address text not null,
  message text not null,
  expires_at timestamptz not null,
  consumed_at timestamptz,
  created_at timestamptz not null default now(),
  attempt_count smallint not null default 0,
  constraint wallet_challenges_wallet_shape check (
    wallet_address ~ '^[1-9A-HJ-NP-Za-km-z]{32,44}$'
  ),
  constraint wallet_challenges_message_length check (char_length(message) between 32 and 4096),
  constraint wallet_challenges_expiry check (expires_at > created_at),
  constraint wallet_challenges_attempts check (attempt_count between 0 and 10)
);

create table if not exists public.wallet_sessions (
  id uuid not null default gen_random_uuid() unique,
  token_hash text primary key,
  wallet_address text not null references public.profiles(wallet_address)
    on update cascade on delete cascade,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  revoked boolean generated always as (revoked_at is not null) stored,
  created_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  constraint wallet_sessions_hash_shape check (token_hash ~ '^[0-9a-f]{64}$'),
  constraint wallet_sessions_expiry check (expires_at > created_at)
);

-- Timestamp, hierarchy, media ownership, aggregate, and donation integrity helpers.
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end
$$;

create or replace function public.validate_comment_parent()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  parent_post_id bigint;
  parent_depth smallint;
begin
  if new.parent_id is null then
    new.depth := 0;
    return new;
  end if;

  if new.id is not null and new.parent_id = new.id then
    raise exception 'A comment cannot reply to itself';
  end if;

  select c.post_id, c.depth
  into parent_post_id, parent_depth
  from public.comments c
  where c.id = new.parent_id;

  if not found then
    raise exception 'Parent comment does not exist';
  end if;
  if parent_post_id <> new.post_id then
    raise exception 'Parent comment belongs to another post';
  end if;
  if parent_depth >= 5 then
    raise exception 'Maximum reply depth is 5';
  end if;

  new.depth := parent_depth + 1;
  return new;
end
$$;

create or replace function public.sync_post_comment_count()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    update public.posts set comment_count = comment_count + 1 where id = new.post_id;
    return new;
  elsif tg_op = 'DELETE' then
    update public.posts set comment_count = greatest(comment_count - 1, 0) where id = old.post_id;
    return old;
  elsif old.post_id is distinct from new.post_id then
    update public.posts set comment_count = greatest(comment_count - 1, 0) where id = old.post_id;
    update public.posts set comment_count = comment_count + 1 where id = new.post_id;
  end if;
  return new;
end
$$;

create or replace function public.validate_media_owner()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  asset_owner text;
  content_owner text;
begin
  select m.owner_wallet into asset_owner
  from public.media_assets m where m.id = new.media_id;

  if tg_table_name = 'post_media' then
    select p.author_wallet into content_owner
    from public.posts p where p.id = new.post_id;
  else
    select c.author_wallet into content_owner
    from public.comments c where c.id = new.comment_id;
  end if;

  if content_owner is null or asset_owner <> content_owner then
    raise exception 'Media owner must match content author';
  end if;
  return new;
end
$$;

create or replace function public.validate_verified_donation_target()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  expected_recipient text;
begin
  if new.target_type = 'post' then
    select p.author_wallet into expected_recipient from public.posts p where p.id = new.post_id;
  elsif new.target_type = 'comment' then
    select c.author_wallet into expected_recipient from public.comments c where c.id = new.comment_id;
  else
    -- The service wallet is configured and verified by the server route.
    return new;
  end if;

  if expected_recipient is null then
    raise exception 'Donation target has no valid recipient wallet';
  end if;
  if new.recipient_wallet <> expected_recipient then
    raise exception 'Verified transfer recipient does not match content recipient';
  end if;
  return new;
end
$$;

create or replace function public.sync_verified_donation_totals()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    if new.target_type = 'post' then
      update public.posts
      set verified_donation_lamports = verified_donation_lamports + new.lamports
      where id = new.post_id;
    elsif new.target_type = 'comment' then
      update public.comments
      set verified_donation_lamports = verified_donation_lamports + new.lamports
      where id = new.comment_id;
    end if;
    return new;
  end if;

  if old.target_type = 'post' then
    update public.posts
    set verified_donation_lamports = greatest(verified_donation_lamports - old.lamports, 0)
    where id = old.post_id;
  elsif old.target_type = 'comment' then
    update public.comments
    set verified_donation_lamports = greatest(verified_donation_lamports - old.lamports, 0)
    where id = old.comment_id;
  end if;
  return old;
end
$$;

create or replace function public.reject_verified_donation_update()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  raise exception 'Verified donation rows are immutable; delete and re-verify instead';
end
$$;

drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at
before update on public.profiles
for each row execute function public.touch_updated_at();

drop trigger if exists posts_touch_updated_at on public.posts;
create trigger posts_touch_updated_at
before update of nickname, body, category on public.posts
for each row execute function public.touch_updated_at();

drop trigger if exists comments_touch_updated_at on public.comments;
create trigger comments_touch_updated_at
before update of nickname, body, parent_id on public.comments
for each row execute function public.touch_updated_at();

drop trigger if exists comments_validate_parent on public.comments;
create trigger comments_validate_parent
before insert or update of parent_id, post_id on public.comments
for each row execute function public.validate_comment_parent();

drop trigger if exists comments_sync_post_count on public.comments;
create trigger comments_sync_post_count
after insert or delete or update of post_id on public.comments
for each row execute function public.sync_post_comment_count();

drop trigger if exists post_media_validate_owner on public.post_media;
create trigger post_media_validate_owner
before insert or update on public.post_media
for each row execute function public.validate_media_owner();

drop trigger if exists comment_media_validate_owner on public.comment_media;
create trigger comment_media_validate_owner
before insert or update on public.comment_media
for each row execute function public.validate_media_owner();

drop trigger if exists donations_validate_target on public.donations;
create trigger donations_validate_target
before insert on public.donations
for each row execute function public.validate_verified_donation_target();

drop trigger if exists donations_sync_totals on public.donations;
create trigger donations_sync_totals
after insert or delete on public.donations
for each row execute function public.sync_verified_donation_totals();

drop trigger if exists donations_immutable on public.donations;
create trigger donations_immutable
before update on public.donations
for each row execute function public.reject_verified_donation_update();

-- Existing comments were loaded before the counter trigger was created.
update public.posts p
set comment_count = x.comment_count
from (
  select p2.id, count(c.id)::bigint as comment_count
  from public.posts p2
  left join public.comments c on c.post_id = p2.id
  group by p2.id
) x
where x.id = p.id;

-- Service-only RPC. The target row lock serializes concurrent toggles, while the
-- normalized primary key guarantees one wallet can like a target only once.
create or replace function public.toggle_like_for_wallet(
  p_wallet_address text,
  p_post_id bigint default null,
  p_comment_id bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  now_liked boolean;
  current_count bigint;
  legacy_count bigint := 0;
begin
  p_wallet_address := btrim(p_wallet_address);
  if p_wallet_address !~ '^[1-9A-HJ-NP-Za-km-z]{32,44}$' then
    raise exception 'Invalid Solana wallet address';
  end if;
  if num_nonnulls(p_post_id, p_comment_id) <> 1 then
    raise exception 'Exactly one of p_post_id or p_comment_id is required';
  end if;
  if not exists (
    select 1 from public.profiles p where p.wallet_address = p_wallet_address
  ) then
    raise exception 'Wallet profile does not exist';
  end if;

  if p_post_id is not null then
    perform 1 from public.posts p where p.id = p_post_id for update;
    if not found then raise exception 'Post does not exist'; end if;

    delete from public.post_likes
    where post_id = p_post_id and wallet_address = p_wallet_address;

    if found then
      now_liked := false;
      update public.posts
      set like_count = greatest(like_count - 1, 0)
      where id = p_post_id
      returning like_count, legacy_unattributed_like_count into current_count, legacy_count;
    else
      insert into public.post_likes (post_id, wallet_address)
      values (p_post_id, p_wallet_address);
      now_liked := true;
      update public.posts set like_count = like_count + 1 where id = p_post_id
      returning like_count, legacy_unattributed_like_count into current_count, legacy_count;
    end if;

    return jsonb_build_object(
      'target', 'post', 'id', p_post_id, 'liked', now_liked,
      'like_count', current_count, 'legacy_like_count', legacy_count,
      'count', current_count + legacy_count
    );
  end if;

  perform 1 from public.comments c where c.id = p_comment_id for update;
  if not found then raise exception 'Comment does not exist'; end if;

  delete from public.comment_likes
  where comment_id = p_comment_id and wallet_address = p_wallet_address;

  if found then
    now_liked := false;
    update public.comments set like_count = greatest(like_count - 1, 0)
    where id = p_comment_id returning like_count into current_count;
  else
    insert into public.comment_likes (comment_id, wallet_address)
    values (p_comment_id, p_wallet_address);
    now_liked := true;
    update public.comments set like_count = like_count + 1
    where id = p_comment_id returning like_count into current_count;
  end if;

  return jsonb_build_object(
    'target', 'comment', 'id', p_comment_id, 'liked', now_liked,
    'like_count', current_count, 'count', current_count
  );
end
$$;

-- Wallet challenge/session RPCs are callable only with the server-side service
-- role. Signature verification remains in the Node route; session establishment
-- atomically consumes the already-verified challenge so it cannot be replayed.
create or replace function public.issue_wallet_challenge(
  p_wallet_address text,
  p_message text,
  p_expires_at timestamptz
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  challenge_id uuid;
begin
  p_wallet_address := btrim(p_wallet_address);
  if p_wallet_address !~ '^[1-9A-HJ-NP-Za-km-z]{32,44}$' then
    raise exception 'Invalid Solana wallet address';
  end if;
  if p_expires_at <= now() or p_expires_at > now() + interval '10 minutes' then
    raise exception 'Challenge expiration must be within 10 minutes';
  end if;
  if char_length(p_message) not between 32 and 4096
     or position(p_wallet_address in p_message) = 0 then
    raise exception 'Challenge message is invalid';
  end if;

  insert into public.wallet_challenges (wallet_address, message, expires_at)
  values (p_wallet_address, p_message, p_expires_at)
  returning id into challenge_id;

  return jsonb_build_object(
    'id', challenge_id,
    'wallet_address', p_wallet_address,
    'message', p_message,
    'expires_at', p_expires_at
  );
end
$$;

create or replace function public.establish_wallet_session(
  p_challenge_id uuid,
  p_wallet_address text,
  p_token_hash text,
  p_session_expires_at timestamptz
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  consumed_id uuid;
begin
  p_wallet_address := btrim(p_wallet_address);
  p_token_hash := lower(btrim(p_token_hash));

  if p_wallet_address !~ '^[1-9A-HJ-NP-Za-km-z]{32,44}$' then
    raise exception 'Invalid Solana wallet address';
  end if;
  if p_token_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'Session token hash must be a SHA-256 hex digest';
  end if;
  if p_session_expires_at <= now()
     or p_session_expires_at > now() + interval '30 days' then
    raise exception 'Session expiration must be within 30 days';
  end if;

  update public.wallet_challenges
  set consumed_at = now(), attempt_count = attempt_count + 1
  where id = p_challenge_id
    and wallet_address = p_wallet_address
    and consumed_at is null
    and expires_at > now()
  returning id into consumed_id;

  if consumed_id is null then
    raise exception 'Challenge is invalid, expired, or already consumed';
  end if;

  insert into public.profiles (wallet_address)
  values (p_wallet_address)
  on conflict (wallet_address) do nothing;

  insert into public.wallet_sessions (
    token_hash, wallet_address, expires_at, revoked_at
  ) values (
    p_token_hash, p_wallet_address, p_session_expires_at, null
  );

  return jsonb_build_object(
    'wallet_address', p_wallet_address,
    'expires_at', p_session_expires_at
  );
end
$$;

create or replace function public.get_wallet_session(p_token_hash text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  session_wallet text;
  session_expiry timestamptz;
begin
  p_token_hash := lower(btrim(p_token_hash));
  if p_token_hash !~ '^[0-9a-f]{64}$' then return null; end if;

  update public.wallet_sessions s
  set last_seen_at = now()
  where s.token_hash = p_token_hash
    and s.revoked_at is null
    and s.expires_at > now()
  returning s.wallet_address, s.expires_at into session_wallet, session_expiry;

  if session_wallet is null then return null; end if;
  return jsonb_build_object(
    'wallet_address', session_wallet,
    'expires_at', session_expiry
  );
end
$$;

create or replace function public.revoke_wallet_session(p_token_hash text)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.wallet_sessions
  set revoked_at = now()
  where token_hash = lower(btrim(p_token_hash)) and revoked_at is null;
  return found;
end
$$;

-- Query-path indexes. Cursor pagination uses (created_at, id), never offset scans.
create index if not exists posts_feed_cursor_idx
  on public.posts (created_at desc, id desc);
create index if not exists posts_author_cursor_idx
  on public.posts (author_wallet, created_at desc, id desc);
create index if not exists posts_category_cursor_idx
  on public.posts (category, created_at desc, id desc);
create index if not exists comments_post_parent_cursor_idx
  on public.comments (post_id, parent_id, created_at, id);
create index if not exists comments_author_cursor_idx
  on public.comments (author_wallet, created_at desc, id desc);
create index if not exists post_likes_wallet_cursor_idx
  on public.post_likes (wallet_address, created_at desc, post_id desc);
create index if not exists comment_likes_wallet_cursor_idx
  on public.comment_likes (wallet_address, created_at desc, comment_id desc);
create index if not exists donations_post_idx
  on public.donations (post_id, created_at desc, signature)
  where post_id is not null;
create index if not exists donations_comment_idx
  on public.donations (comment_id, created_at desc, signature)
  where comment_id is not null;
create index if not exists donations_donor_idx
  on public.donations (donor_wallet, created_at desc, signature);
create index if not exists donations_recipient_idx
  on public.donations (recipient_wallet, created_at desc, signature);
create index if not exists legacy_donations_donor_idx
  on public.legacy_unverified_donations (donor_wallet, post_id);
create index if not exists media_assets_owner_idx
  on public.media_assets (owner_wallet, created_at desc, id);
create index if not exists post_media_position_idx
  on public.post_media (post_id, position);
create index if not exists comment_media_position_idx
  on public.comment_media (comment_id, position);
create index if not exists wallet_challenges_expiry_idx
  on public.wallet_challenges (expires_at)
  where consumed_at is null;
create index if not exists wallet_sessions_wallet_idx
  on public.wallet_sessions (wallet_address, expires_at desc)
  where revoked_at is null;
create index if not exists wallet_sessions_expiry_idx
  on public.wallet_sessions (expires_at)
  where revoked_at is null;

-- Stable read contracts used by the application.
create or replace view public.likes
with (security_invoker = true)
as
select
  'post:' || pl.post_id::text || ':' || pl.wallet_address as id,
  pl.wallet_address,
  pl.post_id,
  null::bigint as comment_id,
  pl.created_at
from public.post_likes pl
union all
select
  'comment:' || cl.comment_id::text || ':' || cl.wallet_address as id,
  cl.wallet_address,
  null::bigint as post_id,
  cl.comment_id,
  cl.created_at
from public.comment_likes cl;

create or replace view public.post_cards
with (security_invoker = true)
as
select
  p.id,
  p.author_wallet,
  p.nickname,
  p.body,
  p.category,
  p.created_at,
  p.updated_at,
  p.image_url as legacy_image_url,
  p.like_count,
  p.legacy_unattributed_like_count as legacy_like_count,
  p.verified_donation_lamports,
  p.legacy_donation_lamports,
  p.comment_count,
  coalesce(m.media, '[]'::jsonb) as media
from public.posts p
left join lateral (
  select jsonb_agg(
    jsonb_build_object(
      'id', a.id,
      'kind', a.kind,
      'public_url', a.public_url,
      'mime_type', a.mime_type,
      'width', a.width,
      'height', a.height,
      'duration_seconds', a.duration_seconds,
      'alt_text', a.alt_text,
      'position', pm.position
    ) order by pm.position, a.created_at
  ) as media
  from public.post_media pm
  join public.media_assets a on a.id = pm.media_id
  where pm.post_id = p.id
) m on true;

create or replace view public.comment_cards
with (security_invoker = true)
as
select
  c.id,
  c.post_id,
  c.parent_id,
  c.author_wallet,
  c.legacy_author_label,
  c.nickname,
  c.body,
  c.created_at,
  c.like_count,
  c.verified_donation_lamports,
  coalesce(m.media, '[]'::jsonb) as media
from public.comments c
left join lateral (
  select jsonb_agg(
    jsonb_build_object(
      'id', a.id,
      'kind', a.kind,
      'public_url', a.public_url,
      'mime_type', a.mime_type,
      'width', a.width,
      'height', a.height,
      'duration_seconds', a.duration_seconds,
      'alt_text', a.alt_text,
      'position', cm.position
    ) order by cm.position, a.created_at
  ) as media
  from public.comment_media cm
  join public.media_assets a on a.id = cm.media_id
  where cm.comment_id = c.id
) m on true;

create or replace view public.profile_stats
with (security_invoker = true)
as
select
  pr.wallet_address,
  pr.display_name,
  pr.bio,
  pr.created_at,
  pr.updated_at,
  coalesce(pc.post_count, 0) as post_count,
  coalesce(cc.comment_count, 0) as comment_count,
  coalesce(lg.likes_given, 0) as likes_given,
  coalesce(vs.sent_lamports, 0) as verified_donated_lamports,
  coalesce(vr.received_lamports, 0) as verified_received_lamports,
  coalesce(ls.sent_lamports, 0) as legacy_donated_lamports,
  coalesce(lr.received_lamports, 0) as legacy_received_lamports
from public.profiles pr
left join lateral (
  select count(*)::bigint as post_count from public.posts p
  where p.author_wallet = pr.wallet_address
) pc on true
left join lateral (
  select count(*)::bigint as comment_count from public.comments c
  where c.author_wallet = pr.wallet_address
) cc on true
left join lateral (
  select (
    (select count(*) from public.post_likes pl where pl.wallet_address = pr.wallet_address)
    + (select count(*) from public.comment_likes cl where cl.wallet_address = pr.wallet_address)
  )::bigint as likes_given
) lg on true
left join lateral (
  select coalesce(sum(d.lamports), 0)::bigint as sent_lamports
  from public.donations d where d.donor_wallet = pr.wallet_address
) vs on true
left join lateral (
  select coalesce(sum(d.lamports), 0)::bigint as received_lamports
  from public.donations d where d.recipient_wallet = pr.wallet_address
) vr on true
left join lateral (
  select coalesce(sum(d.amount_lamports), 0)::bigint as sent_lamports
  from public.legacy_unverified_donations d where d.donor_wallet = pr.wallet_address
) ls on true
left join lateral (
  select coalesce(sum(d.amount_lamports), 0)::bigint as received_lamports
  from public.legacy_unverified_donations d where d.recipient_wallet = pr.wallet_address
) lr on true;

-- Public media is intentionally readable, but only the service role can create,
-- replace, or delete objects. Database metadata enforces the same 15 MiB ceiling.
insert into storage.buckets (
  id, name, public, file_size_limit, allowed_mime_types
) values (
  'media',
  'media',
  true,
  15728640,
  array[
    'image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/avif',
    'audio/webm', 'audio/mpeg', 'audio/mp4', 'audio/ogg', 'audio/wav',
    'video/webm', 'video/mp4', 'video/quicktime'
  ]::text[]
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists media_public_read on storage.objects;
create policy media_public_read
on storage.objects for select
to anon, authenticated
using (bucket_id = 'media');

-- Table grants are a second guardrail: even an accidentally permissive Storage
-- policy cannot authorize browser writes without the corresponding SQL grant.
revoke insert, update, delete, truncate, references, trigger
  on storage.objects from anon, authenticated;
grant select on storage.objects to anon, authenticated;
grant select, insert, update, delete on storage.objects to service_role;

-- Every exposed table is read-only to anon/authenticated. Custom sessions are not
-- Supabase Auth JWTs; all mutations pass through server routes using service_role.
do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'main_test', 'posts', 'post_info', 'comments', 'profiles',
    'post_likes', 'comment_likes', 'donations',
    'legacy_unverified_donations', 'media_assets', 'post_media', 'comment_media'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('revoke all on table public.%I from public, anon, authenticated', table_name);
    execute format('grant select on table public.%I to anon, authenticated', table_name);
    execute format('drop policy if exists public_read on public.%I', table_name);
    execute format(
      'create policy public_read on public.%I for select to anon, authenticated using (true)',
      table_name
    );
  end loop;
end
$$;

drop policy if exists "Enable insert for authenticated users only" on public.posts;
drop policy if exists "Enable read access for all users" on public.posts;

alter table public.wallet_challenges enable row level security;
alter table public.wallet_sessions enable row level security;
revoke all on public.wallet_challenges from public, anon, authenticated;
revoke all on public.wallet_sessions from public, anon, authenticated;
revoke all on internal.legacy_auth_wallet_links from public, anon, authenticated;
grant select, insert, update, delete on public.wallet_challenges to service_role;
grant select, insert, update, delete on public.wallet_sessions to service_role;
grant select, insert, update, delete on internal.legacy_auth_wallet_links to service_role;

grant select, insert, update, delete on
  public.posts, public.comments, public.profiles,
  public.post_likes, public.comment_likes,
  public.donations, public.legacy_unverified_donations,
  public.media_assets, public.post_media, public.comment_media
to service_role;
revoke all on all sequences in schema public from public, anon, authenticated;
grant usage, select on all sequences in schema public to service_role;

revoke all on public.post_cards from public, anon, authenticated;
revoke all on public.comment_cards from public, anon, authenticated;
revoke all on public.profile_stats from public, anon, authenticated;
revoke all on public.likes from public, anon, authenticated;
grant select on public.likes, public.post_cards, public.comment_cards, public.profile_stats
to anon, authenticated, service_role;

revoke all on function public.toggle_like_for_wallet(text, bigint, bigint)
  from public, anon, authenticated;
revoke all on function public.issue_wallet_challenge(text, text, timestamptz)
  from public, anon, authenticated;
revoke all on function public.establish_wallet_session(uuid, text, text, timestamptz)
  from public, anon, authenticated;
revoke all on function public.get_wallet_session(text)
  from public, anon, authenticated;
revoke all on function public.revoke_wallet_session(text)
  from public, anon, authenticated;
grant execute on function public.toggle_like_for_wallet(text, bigint, bigint) to service_role;
grant execute on function public.issue_wallet_challenge(text, text, timestamptz) to service_role;
grant execute on function public.establish_wallet_session(uuid, text, text, timestamptz) to service_role;
grant execute on function public.get_wallet_session(text) to service_role;
grant execute on function public.revoke_wallet_session(text) to service_role;

revoke all on function public.touch_updated_at() from public, anon, authenticated;
revoke all on function public.validate_comment_parent() from public, anon, authenticated;
revoke all on function public.sync_post_comment_count() from public, anon, authenticated;
revoke all on function public.validate_media_owner() from public, anon, authenticated;
revoke all on function public.validate_verified_donation_target() from public, anon, authenticated;
revoke all on function public.sync_verified_donation_totals() from public, anon, authenticated;
revoke all on function public.reject_verified_donation_update() from public, anon, authenticated;

-- Dynamic reconciliation assertions: these remain correct if more legacy rows are
-- created before the coordinated migration window.
do $$
declare
  source_post_likes bigint;
  migrated_post_likes bigint;
  source_comment_likes bigint;
  migrated_comment_likes bigint;
  expected_total_likes bigint;
  migrated_total_likes bigint;
  source_legacy_donations bigint;
  migrated_legacy_donations bigint;
begin
  select count(*) into source_post_likes
  from (
    select pi.id, btrim(l.wallet_address)
    from public.post_info pi
    join public.posts p on p.id = pi.id
    cross join lateral unnest(coalesce(pi.liked_by, array[]::text[])) as l(wallet_address)
    where btrim(coalesce(l.wallet_address, '')) ~ '^[1-9A-HJ-NP-Za-km-z]{32,44}$'
    group by pi.id, btrim(l.wallet_address)
  ) x;
  select count(*) into migrated_post_likes from public.post_likes;
  if migrated_post_likes <> source_post_likes then
    raise exception 'Post-like reconciliation failed: source %, migrated %',
      source_post_likes, migrated_post_likes;
  end if;

  select count(*) into source_comment_likes
  from (
    select c.id, btrim(l.wallet_address)
    from public.comments c
    cross join lateral unnest(coalesce(c.likes, array[]::text[])) as l(wallet_address)
    where btrim(coalesce(l.wallet_address, '')) ~ '^[1-9A-HJ-NP-Za-km-z]{32,44}$'
    group by c.id, btrim(l.wallet_address)
  ) x;
  select count(*) into migrated_comment_likes from public.comment_likes;
  if migrated_comment_likes <> source_comment_likes then
    raise exception 'Comment-like reconciliation failed: source %, migrated %',
      source_comment_likes, migrated_comment_likes;
  end if;

  select coalesce(sum(greatest(coalesce(p.likes, 0), x.exact_count)), 0)
  into expected_total_likes
  from public.posts p
  join (
    select p2.id, count(pl.wallet_address)::bigint as exact_count
    from public.posts p2 left join public.post_likes pl on pl.post_id = p2.id
    group by p2.id
  ) x on x.id = p.id;
  select coalesce(sum(like_count + legacy_unattributed_like_count), 0)
  into migrated_total_likes from public.posts;
  if migrated_total_likes <> expected_total_likes then
    raise exception 'Like-total reconciliation failed: expected %, migrated %',
      expected_total_likes, migrated_total_likes;
  end if;

  select count(*) into source_legacy_donations
  from public.posts p
  cross join lateral jsonb_each(
    case when jsonb_typeof(p.donated) = 'object' then p.donated else '{}'::jsonb end
  ) d;
  select count(*) into migrated_legacy_donations
  from public.legacy_unverified_donations;
  if migrated_legacy_donations <> source_legacy_donations then
    raise exception 'Legacy donation reconciliation failed: source %, migrated %',
      source_legacy_donations, migrated_legacy_donations;
  end if;
end
$$;

commit;
